### ISSUE TITLE
Warn: Check GDEF mark glyph class doesn't have characters that are not marks.

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playpen-Sans#27]
@casasin Please revise the listed glyphs to ensure everything is as expected.

<details>
    <summary>⚠️ <b>WARN</b> Check GDEF mark glyph class doesn't have characters that are not marks. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/opentype.gdef.html#"></a></summary>
    <div>

> 
> Glyphs in the GDEF mark glyph class become non-spacing and may be repositioned
> if they have mark anchors.
> 
> Only combining mark glyphs should be in that class. Any non-mark glyph
> must not be in that class, in particular spacing glyphs.
> 

> Original proposal: https://github.com/fonttools/fontbakery/issues/2877

* ⚠️ **WARN** <p>The following non-mark characters should not be in the GDEF mark glyph class:
U+0384, U+0385, U+FBB2, U+FBB3, U+FBB4, U+FBB5, U+FBB6, U+FBB9, U+FBC0, U+FBC2, U+FC5E, U+FC5F, U+FC60, U+FC61, U+FC62, U+FC63, U+FE70, U+FE72, U+FE74, U+FE76, U+FE78, U+FE7A, U+FE7C and U+FE7E</p>
 [code: non-mark-chars]

</div>
</details>

**Comment by josescaglione** [comment]
@vv-monsalve 
We can disregard this warning (even though we will try to remove it by explicitly marking these as mark)

**Comment by josescaglione** [comment]
OK, an update after more detailed revision:

1. The glyphs listed above ARE combining marks
2. In the glyphs file they are not explicitly set as comb marks but...
3. they have _anchorname and
4. they are width 0 on export
5. and they seem to be correctly in the GDEF mark section

In short, the font is correct and we do not know why FB is flagging these

**Comment by yanone** [comment]
@vv-monsalve asked me to take a look at the WARN above and I agree that it's good to use the legacy encoded Arabic mark glyphs as non-spacing marks as components with anchors.

The alternative would be to duplicate them and use their unencoded siblings as components similar to how we use two sets of diacritics in Latin, but since the encoded glyphs aren't used standalone otherwise, I don't see why one should do that. Using those as components is definitely the common practice.

I assume that the fontbakery check infers glyph definitions from glyphData.xml where they are marked as spacing, which traditionally is correct, but doesn't need to be used like that.

The first two marks in the list are Greek. I assume that the exact same applies. If they are unused as standalone marks, all is good and this issue can be closed.

**Comment by josescaglione** [comment]
@yanone thanks for this.

**Comment by vv-monsalve** [comment]
Thanks, @yanone, for the revision. I'm closing this here.
